const imagePaths = {
  bannerModel: "/images/banner-model.jpg",
  design1: "/images/Design1.svg",
  design2: "/images/Design2.svg",
  brandOne: "/images/brand01.png",
  brandTwo: "/images/brand02.png",
  brandThree: "/images/brand03.png",
  brandFour: "/images/brand04.png",
  brandFive: "/images/brand05.png",
  cardOne: "/images/card1.jpg",
  cardTwo: "/images/card2.jpg",
  cardThree: "/images/card3.jpg",
  cardFour: "/images/card4.jpg",
  cardFive: "/images/card5.jpg",
  cardSix: "/images/card6.jpg",
  followOne: "/images/follow01.png",
  followTwo: "/images/follow02.png",
  followThree: "/images/follow03.png",
  followFour: "/images/follow04.png",
  followFive: "/images/follow05.png",
  followSix: "/images/follow06.png",
  modelOne: "/images/model01.jpg",
  modelTwo: "/images/model02.jpg",
  modelThree: "/images/model03.jpg",
  modelFour: "/images/model04.jpg",
  modelFive: "/images/model05.jpg",
  modelSix: "/images/model06.jpg",
  productOne: "/images/product01.jpg",
  productTwo: "/images/product02.jpg",
  productThree: "/images/product03.jpg",
  productFour: "/images/product04.jpg",
  productFive: "/images/product05.jpg",
  productSix: "/images/product06.jpg",
  productSeven: "/images/product07.jpg",
  productEight: "/images/product08.jpg",

  zaraCover: "/images/zara-cover.jpg",
  zaraOne: "/images/zara1.svg",
  zaraTwo: "/images/zara2.svg",

  paymentIcons: "/images/payments_icons.png",
  notFoundImage: "/images/404.png",
};

export { imagePaths };
